//------------------------------------------------------------------------------
// <auto-generated>
//     This code is generated by the tool.
//     Runtime version:4.0.30319.42000
//
//     Changes to this file may result in incorrect behavior and if
//     Regenerate the code and these changes will be lost.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABPRenamer.Properties {
    using System;


    /// <summary>
    ///   A strongly typed resource class for finding localized strings, and so on.
    /// </summary>
    // This class is made by StronglyTypedResourceBuilder
    // Classes are automatically generated by tools like ResGen or Visual Studio.
    // To add or remove members, edit the .ResX file and rerun ResGen
    // (with /str as a command option), or regenerate the VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns a cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABPRenamer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Override the CurrentUICulture property of the current thread
        ///   Override the CurrentUICulture property of the current thread.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
