using System;
using System.Runtime.InteropServices;
using System.Windows.Forms;

namespace ABPRenamer
{
    partial class FormMain
    {
        /// <summary>
        /// Required designer variables.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up all resources that are in use.
        /// </summary>
        /// <param name="disposing">True if the managed resource should be released; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows The code generated by the form designer

        /// <summary>
        /// Designer supports the required methods - don't modify
        /// Use the code editor to modify the contents of this method.
        /// </summary>
        private void InitializeComponent()
        {
      System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormMain));
      this.lbOriginalName = new System.Windows.Forms.Label();
      this.lbOriginalProjectName = new System.Windows.Forms.Label();
      this.lbProjectPath = new System.Windows.Forms.Label();
      this.txtOldCompanyName = new System.Windows.Forms.TextBox();
      this.txtOldProjectName = new System.Windows.Forms.TextBox();
      this.btnStart = new System.Windows.Forms.Button();
      this.txtNewProjectName = new System.Windows.Forms.TextBox();
      this.txtNewCompanyName = new System.Windows.Forms.TextBox();
      this.lbNewProjectName = new System.Windows.Forms.Label();
      this.lbNewCompanyName = new System.Windows.Forms.Label();
      this.lbArrow2nd = new System.Windows.Forms.Label();
      this.lbArrow1st = new System.Windows.Forms.Label();
      this.btnSelect = new System.Windows.Forms.Button();
      this.backgroundWorker = new System.ComponentModel.BackgroundWorker();
      this.progressBar1 = new System.Windows.Forms.ProgressBar();
      this.btnClose = new System.Windows.Forms.Button();
      this.lbTitle = new System.Windows.Forms.Label();
      this.panel1 = new System.Windows.Forms.Panel();
      this.btnChangeLog = new System.Windows.Forms.Button();
      this.pictureBoxLogo = new System.Windows.Forms.PictureBox();
      this.label9 = new System.Windows.Forms.Label();
      this.Console = new System.Windows.Forms.TextBox();
      this.lbReset = new System.Windows.Forms.Label();
      this.btnReset = new System.Windows.Forms.Button();
      this.txtFilter = new System.Windows.Forms.TextBox();
      this.txtRootDir = new System.Windows.Forms.TextBox();
      this.lbOriginalAreaName = new System.Windows.Forms.Label();
      this.txtOldAreaName = new System.Windows.Forms.TextBox();
      this.lbArrow3rd = new System.Windows.Forms.Label();
      this.lbNewAreaName = new System.Windows.Forms.Label();
      this.txtNewAreaName = new System.Windows.Forms.TextBox();
      this.chk = new System.Windows.Forms.CheckBox();
      this.panel1.SuspendLayout();
      ((System.ComponentModel.ISupportInitialize)(this.pictureBoxLogo)).BeginInit();
      this.SuspendLayout();
      // 
      // lbOriginalName
      // 
      this.lbOriginalName.AutoSize = true;
      this.lbOriginalName.Cursor = System.Windows.Forms.Cursors.Hand;
      this.lbOriginalName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
      this.lbOriginalName.Location = new System.Drawing.Point(12, 574);
      this.lbOriginalName.Name = "lbOriginalName";
      this.lbOriginalName.Size = new System.Drawing.Size(117, 13);
      this.lbOriginalName.TabIndex = 0;
      this.lbOriginalName.Text = "Original company name";
      this.lbOriginalName.Click += new System.EventHandler(this.lbOriginalName_Click);
      // 
      // lbOriginalProjectName
      // 
      this.lbOriginalProjectName.AutoSize = true;
      this.lbOriginalProjectName.Cursor = System.Windows.Forms.Cursors.Hand;
      this.lbOriginalProjectName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
      this.lbOriginalProjectName.Location = new System.Drawing.Point(12, 600);
      this.lbOriginalProjectName.Name = "lbOriginalProjectName";
      this.lbOriginalProjectName.Size = new System.Drawing.Size(106, 13);
      this.lbOriginalProjectName.TabIndex = 1;
      this.lbOriginalProjectName.Text = "Original project name";
      this.lbOriginalProjectName.Click += new System.EventHandler(this.lbOriginalProjectName_Click);
      // 
      // lbProjectPath
      // 
      this.lbProjectPath.AutoSize = true;
      this.lbProjectPath.Cursor = System.Windows.Forms.Cursors.Hand;
      this.lbProjectPath.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
      this.lbProjectPath.Location = new System.Drawing.Point(12, 669);
      this.lbProjectPath.Name = "lbProjectPath";
      this.lbProjectPath.Size = new System.Drawing.Size(64, 13);
      this.lbProjectPath.TabIndex = 2;
      this.lbProjectPath.Text = "Project path";
      this.lbProjectPath.Click += new System.EventHandler(this.lbProjectPath_Click);
      // 
      // txtOldCompanyName
      // 
      this.txtOldCompanyName.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
      this.txtOldCompanyName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
      this.txtOldCompanyName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(193)))), ((int)(((byte)(193)))));
      this.txtOldCompanyName.Location = new System.Drawing.Point(138, 572);
      this.txtOldCompanyName.Name = "txtOldCompanyName";
      this.txtOldCompanyName.Size = new System.Drawing.Size(224, 20);
      this.txtOldCompanyName.TabIndex = 3;
      this.txtOldCompanyName.Text = "MyCompanyName";
      // 
      // txtOldProjectName
      // 
      this.txtOldProjectName.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
      this.txtOldProjectName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
      this.txtOldProjectName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(193)))), ((int)(((byte)(193)))));
      this.txtOldProjectName.Location = new System.Drawing.Point(138, 598);
      this.txtOldProjectName.Name = "txtOldProjectName";
      this.txtOldProjectName.Size = new System.Drawing.Size(224, 20);
      this.txtOldProjectName.TabIndex = 4;
      this.txtOldProjectName.Text = "AbpZeroTemplate";
      // 
      // btnStart
      // 
      this.btnStart.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(187)))), ((int)(((byte)(119)))));
      this.btnStart.Cursor = System.Windows.Forms.Cursors.Hand;
      this.btnStart.FlatAppearance.BorderSize = 0;
      this.btnStart.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
      this.btnStart.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
      this.btnStart.ForeColor = System.Drawing.Color.White;
      this.btnStart.Location = new System.Drawing.Point(539, 650);
      this.btnStart.Name = "btnStart";
      this.btnStart.Size = new System.Drawing.Size(194, 48);
      this.btnStart.TabIndex = 6;
      this.btnStart.Text = "Execute";
      this.btnStart.UseVisualStyleBackColor = false;
      this.btnStart.Click += new System.EventHandler(this.BtnStart_Click);
      // 
      // txtNewProjectName
      // 
      this.txtNewProjectName.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
      this.txtNewProjectName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
      this.txtNewProjectName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(193)))), ((int)(((byte)(193)))));
      this.txtNewProjectName.Location = new System.Drawing.Point(509, 598);
      this.txtNewProjectName.Name = "txtNewProjectName";
      this.txtNewProjectName.Size = new System.Drawing.Size(224, 20);
      this.txtNewProjectName.TabIndex = 11;
      // 
      // txtNewCompanyName
      // 
      this.txtNewCompanyName.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
      this.txtNewCompanyName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
      this.txtNewCompanyName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(193)))), ((int)(((byte)(193)))));
      this.txtNewCompanyName.Location = new System.Drawing.Point(509, 572);
      this.txtNewCompanyName.Name = "txtNewCompanyName";
      this.txtNewCompanyName.Size = new System.Drawing.Size(224, 20);
      this.txtNewCompanyName.TabIndex = 10;
      // 
      // lbNewProjectName
      // 
      this.lbNewProjectName.AutoSize = true;
      this.lbNewProjectName.Cursor = System.Windows.Forms.Cursors.Hand;
      this.lbNewProjectName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
      this.lbNewProjectName.Location = new System.Drawing.Point(410, 600);
      this.lbNewProjectName.Name = "lbNewProjectName";
      this.lbNewProjectName.Size = new System.Drawing.Size(93, 13);
      this.lbNewProjectName.TabIndex = 9;
      this.lbNewProjectName.Text = "New project name";
      this.lbNewProjectName.Click += new System.EventHandler(this.lbNewProjectName_Click);
      // 
      // lbNewCompanyName
      // 
      this.lbNewCompanyName.AutoSize = true;
      this.lbNewCompanyName.Cursor = System.Windows.Forms.Cursors.Hand;
      this.lbNewCompanyName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
      this.lbNewCompanyName.Location = new System.Drawing.Point(399, 574);
      this.lbNewCompanyName.Name = "lbNewCompanyName";
      this.lbNewCompanyName.Size = new System.Drawing.Size(104, 13);
      this.lbNewCompanyName.TabIndex = 8;
      this.lbNewCompanyName.Text = "New company name";
      this.lbNewCompanyName.Click += new System.EventHandler(this.lbNewCompanyName_Click);
      // 
      // lbArrow2nd
      // 
      this.lbArrow2nd.AutoSize = true;
      this.lbArrow2nd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
      this.lbArrow2nd.Location = new System.Drawing.Point(368, 600);
      this.lbArrow2nd.Name = "lbArrow2nd";
      this.lbArrow2nd.Size = new System.Drawing.Size(19, 13);
      this.lbArrow2nd.TabIndex = 12;
      this.lbArrow2nd.Text = "=>";
      // 
      // lbArrow1st
      // 
      this.lbArrow1st.AutoSize = true;
      this.lbArrow1st.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
      this.lbArrow1st.Location = new System.Drawing.Point(368, 574);
      this.lbArrow1st.Name = "lbArrow1st";
      this.lbArrow1st.Size = new System.Drawing.Size(19, 13);
      this.lbArrow1st.TabIndex = 13;
      this.lbArrow1st.Text = "=>";
      // 
      // btnSelect
      // 
      this.btnSelect.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(77)))));
      this.btnSelect.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
      this.btnSelect.Cursor = System.Windows.Forms.Cursors.Hand;
      this.btnSelect.FlatAppearance.BorderSize = 0;
      this.btnSelect.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
      this.btnSelect.ForeColor = System.Drawing.Color.White;
      this.btnSelect.Location = new System.Drawing.Point(458, 663);
      this.btnSelect.Name = "btnSelect";
      this.btnSelect.Size = new System.Drawing.Size(75, 25);
      this.btnSelect.TabIndex = 14;
      this.btnSelect.Text = "Select";
      this.btnSelect.UseVisualStyleBackColor = false;
      this.btnSelect.Click += new System.EventHandler(this.BtnSelect_Click);
      // 
      // backgroundWorker
      // 
      this.backgroundWorker.WorkerReportsProgress = true;
      this.backgroundWorker.WorkerSupportsCancellation = true;
      this.backgroundWorker.DoWork += new System.ComponentModel.DoWorkEventHandler(this.BackgroundWorker_DoWork);
      this.backgroundWorker.ProgressChanged += new System.ComponentModel.ProgressChangedEventHandler(this.BackgroundWorker_ProgressChanged);
      this.backgroundWorker.RunWorkerCompleted += new System.ComponentModel.RunWorkerCompletedEventHandler(this.BackgroundWorker_RunWorkerCompleted);
      // 
      // progressBar1
      // 
      this.progressBar1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(51)))), ((int)(((byte)(51)))));
      this.progressBar1.Dock = System.Windows.Forms.DockStyle.Bottom;
      this.progressBar1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(122)))), ((int)(((byte)(204)))));
      this.progressBar1.Location = new System.Drawing.Point(0, 707);
      this.progressBar1.Margin = new System.Windows.Forms.Padding(0);
      this.progressBar1.Maximum = 2009;
      this.progressBar1.Name = "progressBar1";
      this.progressBar1.RightToLeft = System.Windows.Forms.RightToLeft.No;
      this.progressBar1.Size = new System.Drawing.Size(739, 11);
      this.progressBar1.Step = 1;
      this.progressBar1.Style = System.Windows.Forms.ProgressBarStyle.Continuous;
      this.progressBar1.TabIndex = 15;
      this.progressBar1.Visible = false;
      // 
      // btnClose
      // 
      this.btnClose.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(187)))), ((int)(((byte)(119)))));
      this.btnClose.Cursor = System.Windows.Forms.Cursors.Hand;
      this.btnClose.FlatAppearance.BorderSize = 0;
      this.btnClose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
      this.btnClose.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
      this.btnClose.ForeColor = System.Drawing.Color.White;
      this.btnClose.Location = new System.Drawing.Point(691, 3);
      this.btnClose.Name = "btnClose";
      this.btnClose.Size = new System.Drawing.Size(45, 30);
      this.btnClose.TabIndex = 16;
      this.btnClose.Text = "X";
      this.btnClose.UseVisualStyleBackColor = false;
      this.btnClose.Click += new System.EventHandler(this.BtnClose_Click);
      // 
      // lbTitle
      // 
      this.lbTitle.AutoSize = true;
      this.lbTitle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
      this.lbTitle.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
      this.lbTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
      this.lbTitle.Location = new System.Drawing.Point(135, 10);
      this.lbTitle.Name = "lbTitle";
      this.lbTitle.Size = new System.Drawing.Size(277, 20);
      this.lbTitle.TabIndex = 19;
      this.lbTitle.Text = "AspNetZero Solution Renamer V.2.11";
      this.lbTitle.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Form1_MouseDown);
      // 
      // panel1
      // 
      this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
      this.panel1.Controls.Add(this.btnChangeLog);
      this.panel1.Controls.Add(this.pictureBoxLogo);
      this.panel1.Controls.Add(this.lbTitle);
      this.panel1.Controls.Add(this.btnClose);
      this.panel1.Location = new System.Drawing.Point(0, 0);
      this.panel1.Name = "panel1";
      this.panel1.Size = new System.Drawing.Size(739, 34);
      this.panel1.TabIndex = 20;
      this.panel1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Form1_MouseDown);
      // 
      // btnChangeLog
      // 
      this.btnChangeLog.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(77)))));
      this.btnChangeLog.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
      this.btnChangeLog.Cursor = System.Windows.Forms.Cursors.Hand;
      this.btnChangeLog.FlatAppearance.BorderSize = 0;
      this.btnChangeLog.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
      this.btnChangeLog.ForeColor = System.Drawing.Color.White;
      this.btnChangeLog.Location = new System.Drawing.Point(577, 3);
      this.btnChangeLog.Name = "btnChangeLog";
      this.btnChangeLog.Size = new System.Drawing.Size(108, 31);
      this.btnChangeLog.TabIndex = 26;
      this.btnChangeLog.Text = "Change Log";
      this.btnChangeLog.UseVisualStyleBackColor = false;
      this.btnChangeLog.Click += new System.EventHandler(this.btnChangeLog_Click);
      // 
      // pictureBoxLogo
      // 
      this.pictureBoxLogo.Image = ((System.Drawing.Image)(resources.GetObject("pictureBoxLogo.Image")));
      this.pictureBoxLogo.InitialImage = ((System.Drawing.Image)(resources.GetObject("pictureBoxLogo.InitialImage")));
      this.pictureBoxLogo.Location = new System.Drawing.Point(6, 5);
      this.pictureBoxLogo.Name = "pictureBoxLogo";
      this.pictureBoxLogo.Size = new System.Drawing.Size(80, 30);
      this.pictureBoxLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
      this.pictureBoxLogo.TabIndex = 23;
      this.pictureBoxLogo.TabStop = false;
      // 
      // label9
      // 
      this.label9.AutoSize = true;
      this.label9.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
      this.label9.Location = new System.Drawing.Point(352, 179);
      this.label9.Name = "label9";
      this.label9.Size = new System.Drawing.Size(19, 13);
      this.label9.TabIndex = 21;
      this.label9.Text = "=>";
      // 
      // Console
      // 
      this.Console.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
      this.Console.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
      this.Console.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(218)))), ((int)(((byte)(218)))), ((int)(((byte)(218)))));
      this.Console.ImeMode = System.Windows.Forms.ImeMode.Off;
      this.Console.Location = new System.Drawing.Point(6, 40);
      this.Console.Multiline = true;
      this.Console.Name = "Console";
      this.Console.ReadOnly = true;
      this.Console.ScrollBars = System.Windows.Forms.ScrollBars.Both;
      this.Console.Size = new System.Drawing.Size(727, 496);
      this.Console.TabIndex = 22;
      this.Console.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Form1_MouseDown);
      // 
      // lbReset
      // 
      this.lbReset.AutoSize = true;
      this.lbReset.Cursor = System.Windows.Forms.Cursors.Hand;
      this.lbReset.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
      this.lbReset.Location = new System.Drawing.Point(12, 548);
      this.lbReset.Name = "lbReset";
      this.lbReset.Size = new System.Drawing.Size(102, 13);
      this.lbReset.TabIndex = 23;
      this.lbReset.Text = "Replace file content";
      this.lbReset.Click += new System.EventHandler(this.BtnReset_Click);
      // 
      // btnReset
      // 
      this.btnReset.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(77)))), ((int)(((byte)(77)))), ((int)(((byte)(77)))));
      this.btnReset.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
      this.btnReset.Cursor = System.Windows.Forms.Cursors.Hand;
      this.btnReset.FlatAppearance.BorderSize = 0;
      this.btnReset.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
      this.btnReset.ForeColor = System.Drawing.Color.White;
      this.btnReset.Location = new System.Drawing.Point(652, 542);
      this.btnReset.Name = "btnReset";
      this.btnReset.Size = new System.Drawing.Size(81, 25);
      this.btnReset.TabIndex = 25;
      this.btnReset.Text = "Default";
      this.btnReset.UseVisualStyleBackColor = false;
      this.btnReset.Click += new System.EventHandler(this.BtnReset_Click);
      // 
      // txtFilter
      // 
      this.txtFilter.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
      this.txtFilter.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
      this.txtFilter.Cursor = System.Windows.Forms.Cursors.IBeam;
      this.txtFilter.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(193)))), ((int)(((byte)(193)))));
      this.txtFilter.Location = new System.Drawing.Point(138, 546);
      this.txtFilter.Name = "txtFilter";
      this.txtFilter.Size = new System.Drawing.Size(508, 20);
      this.txtFilter.TabIndex = 24;
      this.txtFilter.Text = ".cs,.cshtml,.js,.ts,.csproj,.sln,.xml,.config,.DotSettings,.json,.xaml,.txt,.html" +
    ",.gitignore,.ps1,.md,.plist";
      // 
      // txtRootDir
      // 
      this.txtRootDir.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
      this.txtRootDir.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
      this.txtRootDir.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(193)))), ((int)(((byte)(193)))));
      this.txtRootDir.Location = new System.Drawing.Point(82, 667);
      this.txtRootDir.Name = "txtRootDir";
      this.txtRootDir.Size = new System.Drawing.Size(370, 20);
      this.txtRootDir.TabIndex = 26;
      // 
      // lbOriginalAreaName
      // 
      this.lbOriginalAreaName.AutoSize = true;
      this.lbOriginalAreaName.Cursor = System.Windows.Forms.Cursors.Hand;
      this.lbOriginalAreaName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
      this.lbOriginalAreaName.Location = new System.Drawing.Point(37, 626);
      this.lbOriginalAreaName.Name = "lbOriginalAreaName";
      this.lbOriginalAreaName.Size = new System.Drawing.Size(95, 13);
      this.lbOriginalAreaName.TabIndex = 27;
      this.lbOriginalAreaName.Text = "Original area name";
      this.lbOriginalAreaName.Click += new System.EventHandler(this.lbOriginalAreaName_Click);
      // 
      // txtOldAreaName
      // 
      this.txtOldAreaName.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
      this.txtOldAreaName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
      this.txtOldAreaName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(193)))), ((int)(((byte)(193)))));
      this.txtOldAreaName.Location = new System.Drawing.Point(138, 624);
      this.txtOldAreaName.Name = "txtOldAreaName";
      this.txtOldAreaName.Size = new System.Drawing.Size(224, 20);
      this.txtOldAreaName.TabIndex = 28;
      this.txtOldAreaName.Text = "AppAreaName";
      // 
      // lbArrow3rd
      // 
      this.lbArrow3rd.AutoSize = true;
      this.lbArrow3rd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
      this.lbArrow3rd.Location = new System.Drawing.Point(368, 628);
      this.lbArrow3rd.Name = "lbArrow3rd";
      this.lbArrow3rd.Size = new System.Drawing.Size(19, 13);
      this.lbArrow3rd.TabIndex = 29;
      this.lbArrow3rd.Text = "=>";
      // 
      // lbNewAreaName
      // 
      this.lbNewAreaName.AutoSize = true;
      this.lbNewAreaName.Cursor = System.Windows.Forms.Cursors.Hand;
      this.lbNewAreaName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(173)))), ((int)(((byte)(173)))));
      this.lbNewAreaName.Location = new System.Drawing.Point(421, 628);
      this.lbNewAreaName.Name = "lbNewAreaName";
      this.lbNewAreaName.Size = new System.Drawing.Size(82, 13);
      this.lbNewAreaName.TabIndex = 30;
      this.lbNewAreaName.Text = "New area name";
      // 
      // txtNewAreaName
      // 
      this.txtNewAreaName.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
      this.txtNewAreaName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
      this.txtNewAreaName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(193)))), ((int)(((byte)(193)))));
      this.txtNewAreaName.Location = new System.Drawing.Point(509, 624);
      this.txtNewAreaName.Name = "txtNewAreaName";
      this.txtNewAreaName.Size = new System.Drawing.Size(224, 20);
      this.txtNewAreaName.TabIndex = 31;
      this.txtNewAreaName.Text = "App";
      // 
      // chk
      // 
      this.chk.AutoSize = true;
      this.chk.Checked = true;
      this.chk.CheckState = System.Windows.Forms.CheckState.Checked;
      this.chk.Location = new System.Drawing.Point(16, 626);
      this.chk.Name = "chk";
      this.chk.Size = new System.Drawing.Size(15, 14);
      this.chk.TabIndex = 32;
      this.chk.UseVisualStyleBackColor = true;
      this.chk.CheckedChanged += new System.EventHandler(this.chk_CheckedChanged);
      // 
      // FormMain
      // 
      this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
      this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
      this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(51)))), ((int)(((byte)(51)))));
      this.ClientSize = new System.Drawing.Size(739, 718);
      this.Controls.Add(this.chk);
      this.Controls.Add(this.txtNewAreaName);
      this.Controls.Add(this.lbNewAreaName);
      this.Controls.Add(this.lbArrow3rd);
      this.Controls.Add(this.txtOldAreaName);
      this.Controls.Add(this.lbOriginalAreaName);
      this.Controls.Add(this.txtRootDir);
      this.Controls.Add(this.btnReset);
      this.Controls.Add(this.txtFilter);
      this.Controls.Add(this.lbReset);
      this.Controls.Add(this.Console);
      this.Controls.Add(this.label9);
      this.Controls.Add(this.progressBar1);
      this.Controls.Add(this.btnSelect);
      this.Controls.Add(this.lbArrow1st);
      this.Controls.Add(this.lbArrow2nd);
      this.Controls.Add(this.txtNewProjectName);
      this.Controls.Add(this.txtNewCompanyName);
      this.Controls.Add(this.lbNewProjectName);
      this.Controls.Add(this.lbNewCompanyName);
      this.Controls.Add(this.btnStart);
      this.Controls.Add(this.txtOldProjectName);
      this.Controls.Add(this.txtOldCompanyName);
      this.Controls.Add(this.lbProjectPath);
      this.Controls.Add(this.lbOriginalProjectName);
      this.Controls.Add(this.lbOriginalName);
      this.Controls.Add(this.panel1);
      this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
      this.ImeMode = System.Windows.Forms.ImeMode.Off;
      this.MaximizeBox = false;
      this.MinimizeBox = false;
      this.Name = "FormMain";
      this.ShowIcon = false;
      this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
      this.Text = "AspNetZero Solution Renamer";
      this.Load += new System.EventHandler(this.FormMain_Load);
      this.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Form1_MouseDown);
      this.panel1.ResumeLayout(false);
      this.panel1.PerformLayout();
      ((System.ComponentModel.ISupportInitialize)(this.pictureBoxLogo)).EndInit();
      this.ResumeLayout(false);
      this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lbOriginalName;
        private System.Windows.Forms.Label lbOriginalProjectName;
        private System.Windows.Forms.Label lbProjectPath;
        private System.Windows.Forms.TextBox txtOldCompanyName;
        private System.Windows.Forms.TextBox txtOldProjectName;
        private System.Windows.Forms.Button btnStart;
        private System.Windows.Forms.TextBox txtNewProjectName;
        private System.Windows.Forms.TextBox txtNewCompanyName;
        private System.Windows.Forms.Label lbNewProjectName;
        private System.Windows.Forms.Label lbNewCompanyName;
        private System.Windows.Forms.Label lbArrow2nd;
        private System.Windows.Forms.Label lbArrow1st;
        private System.Windows.Forms.Button btnSelect;
        private System.ComponentModel.BackgroundWorker backgroundWorker;
        private Button btnClose;
        private ProgressBar progressBar1;
        private Label lbTitle;
        private Panel panel1;
        private Label label9;

        #region The main interface can move
        /// 
        //Define a borderless form Form
        [DllImport("user32.dll")]
        //Drag a formless control
        public static extern bool ReleaseCapture();
        [DllImport("user32.dll")]
        public static extern bool SendMessage(IntPtr hwnd, int wMsg, int wParam, int lParam);
        public const int WM_SYSCOMMAND = 0x0112; public const int SC_MOVE = 0xF010; public const int HTCAPTION = 0x0002;
        private void Form1_MouseDown(object sender, MouseEventArgs e)
        {
            ReleaseCapture();
            //Call to move the no-form control function
            SendMessage(Handle, WM_SYSCOMMAND, SC_MOVE + HTCAPTION, 0);

        }
        #endregion

       
       

        private TextBox Console;
        private PictureBox pictureBoxLogo;
        private Label lbReset;
        private Button btnReset;
        private TextBox txtFilter;
        private TextBox txtRootDir;
    private Label lbOriginalAreaName;
    private TextBox txtOldAreaName;
    private Label lbArrow3rd;
    private Label lbNewAreaName;
    private TextBox txtNewAreaName;
    private CheckBox chk;
    private Button btnChangeLog;
  }
}

